name: Sync with Upstream

on:
  schedule:
    - cron: '0 */2 * * *' # 每2小时执行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/Mursor/LIVE.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          # 检查上游是否有新提交
          if git log origin/main..upstream/main | grep 'commit'; then
            echo "发现新提交，开始合并..."
            # 使用rebase合并，并设置冲突时优先保留上游更改
            git pull upstream main --rebase --strategy-option=theirs
            echo "✅ 合并完成"
          else
            echo "ℹ️ 已是最新版本，无需同步"
          fi

      - name: Push to Fork
        run: |
          git push origin main --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
